<?php
/**
 * InstanceConfig
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.14
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * InstanceConfig Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class InstanceConfig implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'InstanceConfig';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'incoming_streams' => '\Swagger\Client\Model\IncomingStreamConfig[]',
        'name' => 'string',
        'outgoing_streams' => '\Swagger\Client\Model\OutgoingStreamConfig[]',
        'server_name' => 'string',
        'stream_groups' => '\Swagger\Client\Model\StreamGroupConfig[]',
        'save_field_list' => 'string[]',
        'version' => 'string',
        'recorders' => '\Swagger\Client\Model\StreamRecorderConfig[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'incoming_streams' => null,
        'name' => null,
        'outgoing_streams' => null,
        'server_name' => null,
        'stream_groups' => null,
        'save_field_list' => null,
        'version' => null,
        'recorders' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'incoming_streams' => 'incomingStreams',
        'name' => 'name',
        'outgoing_streams' => 'outgoingStreams',
        'server_name' => 'serverName',
        'stream_groups' => 'streamGroups',
        'save_field_list' => 'saveFieldList',
        'version' => 'version',
        'recorders' => 'recorders'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'incoming_streams' => 'setIncomingStreams',
        'name' => 'setName',
        'outgoing_streams' => 'setOutgoingStreams',
        'server_name' => 'setServerName',
        'stream_groups' => 'setStreamGroups',
        'save_field_list' => 'setSaveFieldList',
        'version' => 'setVersion',
        'recorders' => 'setRecorders'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'incoming_streams' => 'getIncomingStreams',
        'name' => 'getName',
        'outgoing_streams' => 'getOutgoingStreams',
        'server_name' => 'getServerName',
        'stream_groups' => 'getStreamGroups',
        'save_field_list' => 'getSaveFieldList',
        'version' => 'getVersion',
        'recorders' => 'getRecorders'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['incoming_streams'] = isset($data['incoming_streams']) ? $data['incoming_streams'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['outgoing_streams'] = isset($data['outgoing_streams']) ? $data['outgoing_streams'] : null;
        $this->container['server_name'] = isset($data['server_name']) ? $data['server_name'] : null;
        $this->container['stream_groups'] = isset($data['stream_groups']) ? $data['stream_groups'] : null;
        $this->container['save_field_list'] = isset($data['save_field_list']) ? $data['save_field_list'] : null;
        $this->container['version'] = isset($data['version']) ? $data['version'] : null;
        $this->container['recorders'] = isset($data['recorders']) ? $data['recorders'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['incoming_streams'] === null) {
            $invalidProperties[] = "'incoming_streams' can't be null";
        }
        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['outgoing_streams'] === null) {
            $invalidProperties[] = "'outgoing_streams' can't be null";
        }
        if ($this->container['server_name'] === null) {
            $invalidProperties[] = "'server_name' can't be null";
        }
        if ($this->container['stream_groups'] === null) {
            $invalidProperties[] = "'stream_groups' can't be null";
        }
        if ($this->container['version'] === null) {
            $invalidProperties[] = "'version' can't be null";
        }
        if ($this->container['recorders'] === null) {
            $invalidProperties[] = "'recorders' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets incoming_streams
     *
     * @return \Swagger\Client\Model\IncomingStreamConfig[]
     */
    public function getIncomingStreams()
    {
        return $this->container['incoming_streams'];
    }

    /**
     * Sets incoming_streams
     *
     * @param \Swagger\Client\Model\IncomingStreamConfig[] $incoming_streams incoming_streams
     *
     * @return $this
     */
    public function setIncomingStreams($incoming_streams)
    {
        $this->container['incoming_streams'] = $incoming_streams;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets outgoing_streams
     *
     * @return \Swagger\Client\Model\OutgoingStreamConfig[]
     */
    public function getOutgoingStreams()
    {
        return $this->container['outgoing_streams'];
    }

    /**
     * Sets outgoing_streams
     *
     * @param \Swagger\Client\Model\OutgoingStreamConfig[] $outgoing_streams outgoing_streams
     *
     * @return $this
     */
    public function setOutgoingStreams($outgoing_streams)
    {
        $this->container['outgoing_streams'] = $outgoing_streams;

        return $this;
    }

    /**
     * Gets server_name
     *
     * @return string
     */
    public function getServerName()
    {
        return $this->container['server_name'];
    }

    /**
     * Sets server_name
     *
     * @param string $server_name server_name
     *
     * @return $this
     */
    public function setServerName($server_name)
    {
        $this->container['server_name'] = $server_name;

        return $this;
    }

    /**
     * Gets stream_groups
     *
     * @return \Swagger\Client\Model\StreamGroupConfig[]
     */
    public function getStreamGroups()
    {
        return $this->container['stream_groups'];
    }

    /**
     * Sets stream_groups
     *
     * @param \Swagger\Client\Model\StreamGroupConfig[] $stream_groups stream_groups
     *
     * @return $this
     */
    public function setStreamGroups($stream_groups)
    {
        $this->container['stream_groups'] = $stream_groups;

        return $this;
    }

    /**
     * Gets save_field_list
     *
     * @return string[]
     */
    public function getSaveFieldList()
    {
        return $this->container['save_field_list'];
    }

    /**
     * Sets save_field_list
     *
     * @param string[] $save_field_list save_field_list
     *
     * @return $this
     */
    public function setSaveFieldList($save_field_list)
    {
        $this->container['save_field_list'] = $save_field_list;

        return $this;
    }

    /**
     * Gets version
     *
     * @return string
     */
    public function getVersion()
    {
        return $this->container['version'];
    }

    /**
     * Sets version
     *
     * @param string $version version
     *
     * @return $this
     */
    public function setVersion($version)
    {
        $this->container['version'] = $version;

        return $this;
    }

    /**
     * Gets recorders
     *
     * @return \Swagger\Client\Model\StreamRecorderConfig[]
     */
    public function getRecorders()
    {
        return $this->container['recorders'];
    }

    /**
     * Sets recorders
     *
     * @param \Swagger\Client\Model\StreamRecorderConfig[] $recorders recorders
     *
     * @return $this
     */
    public function setRecorders($recorders)
    {
        $this->container['recorders'] = $recorders;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


