<?php
/**
 * ApplicationConfigTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.14
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ApplicationConfigTest Class Doc Comment
 *
 * @category    Class
 * @description ApplicationConfig
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ApplicationConfigTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ApplicationConfig"
     */
    public function testApplicationConfig()
    {
    }

    /**
     * Test attribute "http_optimize_file_reads"
     */
    public function testPropertyHttpOptimizeFileReads()
    {
    }

    /**
     * Test attribute "caption_live_ıngest_type"
     */
    public function testPropertyCaptionLiveIngestType()
    {
    }

    /**
     * Test attribute "stream_config"
     */
    public function testPropertyStreamConfig()
    {
    }

    /**
     * Test attribute "server_name"
     */
    public function testPropertyServerName()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "media_cache_source_list"
     */
    public function testPropertyMediaCacheSourceList()
    {
    }

    /**
     * Test attribute "repeater_origin_url"
     */
    public function testPropertyRepeaterOriginUrl()
    {
    }

    /**
     * Test attribute "client_stream_read_access"
     */
    public function testPropertyClientStreamReadAccess()
    {
    }

    /**
     * Test attribute "app_type"
     */
    public function testPropertyAppType()
    {
    }

    /**
     * Test attribute "ping_timeout"
     */
    public function testPropertyPingTimeout()
    {
    }

    /**
     * Test attribute "vod_timed_text_providers"
     */
    public function testPropertyVodTimedTextProviders()
    {
    }

    /**
     * Test attribute "save_field_list"
     */
    public function testPropertySaveFieldList()
    {
    }

    /**
     * Test attribute "media_reader_random_access_reader_class"
     */
    public function testPropertyMediaReaderRandomAccessReaderClass()
    {
    }

    /**
     * Test attribute "media_reader_buffer_seek_ıo"
     */
    public function testPropertyMediaReaderBufferSeekIo()
    {
    }

    /**
     * Test attribute "http_streamers"
     */
    public function testPropertyHttpStreamers()
    {
    }

    /**
     * Test attribute "http_cors_headers_enabled"
     */
    public function testPropertyHttpCorsHeadersEnabled()
    {
    }

    /**
     * Test attribute "av_sync_method"
     */
    public function testPropertyAvSyncMethod()
    {
    }

    /**
     * Test attribute "transcoder_config"
     */
    public function testPropertyTranscoderConfig()
    {
    }

    /**
     * Test attribute "client_stream_write_access"
     */
    public function testPropertyClientStreamWriteAccess()
    {
    }

    /**
     * Test attribute "repeater_query_string"
     */
    public function testPropertyRepeaterQueryString()
    {
    }

    /**
     * Test attribute "drm_config"
     */
    public function testPropertyDrmConfig()
    {
    }

    /**
     * Test attribute "version"
     */
    public function testPropertyVersion()
    {
    }

    /**
     * Test attribute "modules"
     */
    public function testPropertyModules()
    {
    }

    /**
     * Test attribute "max_rtcp_wait_time"
     */
    public function testPropertyMaxRtcpWaitTime()
    {
    }

    /**
     * Test attribute "security_config"
     */
    public function testPropertySecurityConfig()
    {
    }

    /**
     * Test attribute "dvr_config"
     */
    public function testPropertyDvrConfig()
    {
    }

    /**
     * Test attribute "application_timeout"
     */
    public function testPropertyApplicationTimeout()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }
}
