<?php
/**
 * DRMConfigTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.14
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * DRMConfigTest Class Doc Comment
 *
 * @category    Class
 * @description DRMConfig
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DRMConfigTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DRMConfig"
     */
    public function testDRMConfig()
    {
    }

    /**
     * Test attribute "buy_drm_protect_mpeg_dash_streaming"
     */
    public function testPropertyBuyDrmProtectMpegDashStreaming()
    {
    }

    /**
     * Test attribute "server_name"
     */
    public function testPropertyServerName()
    {
    }

    /**
     * Test attribute "buy_drm_protect_cupertino_streaming"
     */
    public function testPropertyBuyDrmProtectCupertinoStreaming()
    {
    }

    /**
     * Test attribute "version"
     */
    public function testPropertyVersion()
    {
    }

    /**
     * Test attribute "verimatrix_cupertino_key_server_port"
     */
    public function testPropertyVerimatrixCupertinoKeyServerPort()
    {
    }

    /**
     * Test attribute "verimatrix_smooth_key_server_port"
     */
    public function testPropertyVerimatrixSmoothKeyServerPort()
    {
    }

    /**
     * Test attribute "verimatrix_stream_maps"
     */
    public function testPropertyVerimatrixStreamMaps()
    {
    }

    /**
     * Test attribute "verimatrix_smooth_key_server_ıp_address"
     */
    public function testPropertyVerimatrixSmoothKeyServerIpAddress()
    {
    }

    /**
     * Test attribute "license_type"
     */
    public function testPropertyLicenseType()
    {
    }

    /**
     * Test attribute "verimatrix_cupertino_key_server_ıp_address"
     */
    public function testPropertyVerimatrixCupertinoKeyServerIpAddress()
    {
    }

    /**
     * Test attribute "buy_drm_protect_smooth_streaming"
     */
    public function testPropertyBuyDrmProtectSmoothStreaming()
    {
    }

    /**
     * Test attribute "buy_drm_user_key"
     */
    public function testPropertyBuyDrmUserKey()
    {
    }

    /**
     * Test attribute "in_use"
     */
    public function testPropertyInUse()
    {
    }

    /**
     * Test attribute "ez_drm_username"
     */
    public function testPropertyEzDrmUsername()
    {
    }

    /**
     * Test attribute "verimatrix_protect_smooth_streaming"
     */
    public function testPropertyVerimatrixProtectSmoothStreaming()
    {
    }

    /**
     * Test attribute "buy_drm_stream_maps"
     */
    public function testPropertyBuyDrmStreamMaps()
    {
    }

    /**
     * Test attribute "verimatrix_cupertino_vod_per_session_keys"
     */
    public function testPropertyVerimatrixCupertinoVodPerSessionKeys()
    {
    }

    /**
     * Test attribute "save_field_list"
     */
    public function testPropertySaveFieldList()
    {
    }

    /**
     * Test attribute "ez_drm_password"
     */
    public function testPropertyEzDrmPassword()
    {
    }

    /**
     * Test attribute "verimatrix_protect_cupertino_streaming"
     */
    public function testPropertyVerimatrixProtectCupertinoStreaming()
    {
    }

    /**
     * Test attribute "cupertino_encryption_apı_based"
     */
    public function testPropertyCupertinoEncryptionApıBased()
    {
    }
}
