<?php
/**
 * IncomingStreamConfigTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.14
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * IncomingStreamConfigTest Class Doc Comment
 *
 * @category    Class
 * @description IncomingStreamConfig
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class IncomingStreamConfigTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "IncomingStreamConfig"
     */
    public function testIncomingStreamConfig()
    {
    }

    /**
     * Test attribute "ptz_polling_ınterval_minimum"
     */
    public function testPropertyPtzPollingIntervalMinimum()
    {
    }

    /**
     * Test attribute "application_ınstance"
     */
    public function testPropertyApplicationInstance()
    {
    }

    /**
     * Test attribute "is_ptz_enabled"
     */
    public function testPropertyIsPtzEnabled()
    {
    }

    /**
     * Test attribute "is_connected"
     */
    public function testPropertyIsConnected()
    {
    }

    /**
     * Test attribute "server_name"
     */
    public function testPropertyServerName()
    {
    }

    /**
     * Test attribute "version"
     */
    public function testPropertyVersion()
    {
    }

    /**
     * Test attribute "ptz_polling_ınterval"
     */
    public function testPropertyPtzPollingInterval()
    {
    }

    /**
     * Test attribute "is_recording_set"
     */
    public function testPropertyIsRecordingSet()
    {
    }

    /**
     * Test attribute "source_ıp"
     */
    public function testPropertySourceIp()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "is_published_to_vod"
     */
    public function testPropertyIsPublishedToVod()
    {
    }

    /**
     * Test attribute "save_field_list"
     */
    public function testPropertySaveFieldList()
    {
    }

    /**
     * Test attribute "is_stream_manager_stream"
     */
    public function testPropertyIsStreamManagerStream()
    {
    }
}
