<?php
/**
 * ServerLogFileConfigTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.14
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ServerLogFileConfigTest Class Doc Comment
 *
 * @category    Class
 * @description ServerLogFileConfig
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ServerLogFileConfigTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ServerLogFileConfig"
     */
    public function testServerLogFileConfig()
    {
    }

    /**
     * Test attribute "end_offset"
     */
    public function testPropertyEndOffset()
    {
    }

    /**
     * Test attribute "log_start_date"
     */
    public function testPropertyLogStartDate()
    {
    }

    /**
     * Test attribute "log_date"
     */
    public function testPropertyLogDate()
    {
    }

    /**
     * Test attribute "end_date"
     */
    public function testPropertyEndDate()
    {
    }

    /**
     * Test attribute "server_name"
     */
    public function testPropertyServerName()
    {
    }

    /**
     * Test attribute "version"
     */
    public function testPropertyVersion()
    {
    }

    /**
     * Test attribute "log_lines"
     */
    public function testPropertyLogLines()
    {
    }

    /**
     * Test attribute "filter_str"
     */
    public function testPropertyFilterStr()
    {
    }

    /**
     * Test attribute "ret_line_count"
     */
    public function testPropertyRetLineCount()
    {
    }

    /**
     * Test attribute "log_fields"
     */
    public function testPropertyLogFields()
    {
    }

    /**
     * Test attribute "log_software"
     */
    public function testPropertyLogSoftware()
    {
    }

    /**
     * Test attribute "start_offset"
     */
    public function testPropertyStartOffset()
    {
    }

    /**
     * Test attribute "search_str"
     */
    public function testPropertySearchStr()
    {
    }

    /**
     * Test attribute "regex_search"
     */
    public function testPropertyRegexSearch()
    {
    }

    /**
     * Test attribute "log_version"
     */
    public function testPropertyLogVersion()
    {
    }

    /**
     * Test attribute "save_field_list"
     */
    public function testPropertySaveFieldList()
    {
    }

    /**
     * Test attribute "file_length"
     */
    public function testPropertyFileLength()
    {
    }

    /**
     * Test attribute "start_date"
     */
    public function testPropertyStartDate()
    {
    }
}
