<?php
/**
 * SSLConfigTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.14
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * SSLConfigTest Class Doc Comment
 *
 * @category    Class
 * @description SSLConfig
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SSLConfigTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SSLConfig"
     */
    public function testSSLConfig()
    {
    }

    /**
     * Test attribute "ssl_key_store_password"
     */
    public function testPropertySslKeyStorePassword()
    {
    }

    /**
     * Test attribute "ssl_protocols"
     */
    public function testPropertySslProtocols()
    {
    }

    /**
     * Test attribute "ssl_domain_to_key_store_map_path"
     */
    public function testPropertySslDomainToKeyStoreMapPath()
    {
    }

    /**
     * Test attribute "ssl_cipher_suites"
     */
    public function testPropertySslCipherSuites()
    {
    }

    /**
     * Test attribute "server_name"
     */
    public function testPropertyServerName()
    {
    }

    /**
     * Test attribute "ssl_key_store_type"
     */
    public function testPropertySslKeyStoreType()
    {
    }

    /**
     * Test attribute "ssl_protocol"
     */
    public function testPropertySslProtocol()
    {
    }

    /**
     * Test attribute "ssl_algorithm"
     */
    public function testPropertySslAlgorithm()
    {
    }

    /**
     * Test attribute "save_field_list"
     */
    public function testPropertySaveFieldList()
    {
    }

    /**
     * Test attribute "ssl_key_store_path"
     */
    public function testPropertySslKeyStorePath()
    {
    }

    /**
     * Test attribute "version"
     */
    public function testPropertyVersion()
    {
    }

    /**
     * Test attribute "ssl_enable"
     */
    public function testPropertySslEnable()
    {
    }
}
