<?php
/**
 * StreamConfigurationConfigTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.14
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * StreamConfigurationConfigTest Class Doc Comment
 *
 * @category    Class
 * @description StreamConfigurationConfig
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class StreamConfigurationConfigTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "StreamConfigurationConfig"
     */
    public function testStreamConfigurationConfig()
    {
    }

    /**
     * Test attribute "stream_type"
     */
    public function testPropertyStreamType()
    {
    }

    /**
     * Test attribute "storage_dir_exists"
     */
    public function testPropertyStorageDirExists()
    {
    }

    /**
     * Test attribute "key_dir"
     */
    public function testPropertyKeyDir()
    {
    }

    /**
     * Test attribute "create_storage_dir"
     */
    public function testPropertyCreateStorageDir()
    {
    }

    /**
     * Test attribute "live_stream_packetizer"
     */
    public function testPropertyLiveStreamPacketizer()
    {
    }

    /**
     * Test attribute "server_name"
     */
    public function testPropertyServerName()
    {
    }

    /**
     * Test attribute "storage_dir"
     */
    public function testPropertyStorageDir()
    {
    }

    /**
     * Test attribute "save_field_list"
     */
    public function testPropertySaveFieldList()
    {
    }

    /**
     * Test attribute "version"
     */
    public function testPropertyVersion()
    {
    }

    /**
     * Test attribute "http_randomize_media_name"
     */
    public function testPropertyHttpRandomizeMediaName()
    {
    }
}
