<?php
/**
 * TranscoderEncodeAppConfigTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.14
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * TranscoderEncodeAppConfigTest Class Doc Comment
 *
 * @category    Class
 * @description TranscoderEncodeAppConfig
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TranscoderEncodeAppConfigTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TranscoderEncodeAppConfig"
     */
    public function testTranscoderEncodeAppConfig()
    {
    }

    /**
     * Test attribute "follow_source"
     */
    public function testPropertyFollowSource()
    {
    }

    /**
     * Test attribute "implementation"
     */
    public function testPropertyImplementation()
    {
    }

    /**
     * Test attribute "gpuid"
     */
    public function testPropertyGpuid()
    {
    }

    /**
     * Test attribute "profile"
     */
    public function testPropertyProfile()
    {
    }

    /**
     * Test attribute "server_name"
     */
    public function testPropertyServerName()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "audio_codec"
     */
    public function testPropertyAudioCodec()
    {
    }

    /**
     * Test attribute "version"
     */
    public function testPropertyVersion()
    {
    }

    /**
     * Test attribute "stream_name"
     */
    public function testPropertyStreamName()
    {
    }

    /**
     * Test attribute "overlays"
     */
    public function testPropertyOverlays()
    {
    }

    /**
     * Test attribute "audio_bitrate"
     */
    public function testPropertyAudioBitrate()
    {
    }

    /**
     * Test attribute "video_bitrate"
     */
    public function testPropertyVideoBitrate()
    {
    }

    /**
     * Test attribute "enable"
     */
    public function testPropertyEnable()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "width"
     */
    public function testPropertyWidth()
    {
    }

    /**
     * Test attribute "interval"
     */
    public function testPropertyInterval()
    {
    }

    /**
     * Test attribute "fit_mode"
     */
    public function testPropertyFitMode()
    {
    }

    /**
     * Test attribute "save_field_list"
     */
    public function testPropertySaveFieldList()
    {
    }

    /**
     * Test attribute "crop"
     */
    public function testPropertyCrop()
    {
    }

    /**
     * Test attribute "video_codec"
     */
    public function testPropertyVideoCodec()
    {
    }

    /**
     * Test attribute "height"
     */
    public function testPropertyHeight()
    {
    }

    /**
     * Test attribute "source_rectangle"
     */
    public function testPropertySourceRectangle()
    {
    }
}
