<?php
/**
 * TranscoderMemberConfigTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.14
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * TranscoderMemberConfigTest Class Doc Comment
 *
 * @category    Class
 * @description TranscoderMemberConfig
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TranscoderMemberConfigTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TranscoderMemberConfig"
     */
    public function testTranscoderMemberConfig()
    {
    }

    /**
     * Test attribute "wowza_video_only"
     */
    public function testPropertyWowzaVideoOnly()
    {
    }

    /**
     * Test attribute "encode_name"
     */
    public function testPropertyEncodeName()
    {
    }

    /**
     * Test attribute "wowza_audio_only"
     */
    public function testPropertyWowzaAudioOnly()
    {
    }

    /**
     * Test attribute "server_name"
     */
    public function testPropertyServerName()
    {
    }

    /**
     * Test attribute "member_name"
     */
    public function testPropertyMemberName()
    {
    }

    /**
     * Test attribute "save_field_list"
     */
    public function testPropertySaveFieldList()
    {
    }

    /**
     * Test attribute "version"
     */
    public function testPropertyVersion()
    {
    }
}
