<?php
/**
 * VHostTuneConfigTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.14
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * VHostTuneConfigTest Class Doc Comment
 *
 * @category    Class
 * @description VHostTuneConfig
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class VHostTuneConfigTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "VHostTuneConfig"
     */
    public function testVHostTuneConfig()
    {
    }

    /**
     * Test attribute "multicast_outgoing_processor_count_auto_value"
     */
    public function testPropertyMulticastOutgoingProcessorCountAutoValue()
    {
    }

    /**
     * Test attribute "net_connections_processor_count_auto_value"
     */
    public function testPropertyNetConnectionsProcessorCountAutoValue()
    {
    }

    /**
     * Test attribute "idle_worker_count_auto_value"
     */
    public function testPropertyIdleWorkerCountAutoValue()
    {
    }

    /**
     * Test attribute "unicast_ıncoming_processor_count_auto_value"
     */
    public function testPropertyUnicastIncomingProcessorCountAutoValue()
    {
    }

    /**
     * Test attribute "unicast_outgoing_processor_count_auto_value"
     */
    public function testPropertyUnicastOutgoingProcessorCountAutoValue()
    {
    }

    /**
     * Test attribute "media_caster_processor_count"
     */
    public function testPropertyMediaCasterProcessorCount()
    {
    }

    /**
     * Test attribute "server_name"
     */
    public function testPropertyServerName()
    {
    }

    /**
     * Test attribute "multicast_outgoing_processor_count"
     */
    public function testPropertyMulticastOutgoingProcessorCount()
    {
    }

    /**
     * Test attribute "multicast_ıncoming_processor_count_auto_value"
     */
    public function testPropertyMulticastIncomingProcessorCountAutoValue()
    {
    }

    /**
     * Test attribute "version"
     */
    public function testPropertyVersion()
    {
    }

    /**
     * Test attribute "net_connections_processor_count"
     */
    public function testPropertyNetConnectionsProcessorCount()
    {
    }

    /**
     * Test attribute "unicast_outgoing_processor_count"
     */
    public function testPropertyUnicastOutgoingProcessorCount()
    {
    }

    /**
     * Test attribute "media_caster_processor_count_auto_value"
     */
    public function testPropertyMediaCasterProcessorCountAutoValue()
    {
    }

    /**
     * Test attribute "idle_worker_count"
     */
    public function testPropertyIdleWorkerCount()
    {
    }

    /**
     * Test attribute "transport_thread_pool_size"
     */
    public function testPropertyTransportThreadPoolSize()
    {
    }

    /**
     * Test attribute "client_ıdle_frequency"
     */
    public function testPropertyClientIdleFrequency()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "unicast_ıncoming_processor_count"
     */
    public function testPropertyUnicastIncomingProcessorCount()
    {
    }

    /**
     * Test attribute "save_field_list"
     */
    public function testPropertySaveFieldList()
    {
    }

    /**
     * Test attribute "multicast_ıncoming_processor_count"
     */
    public function testPropertyMulticastIncomingProcessorCount()
    {
    }

    /**
     * Test attribute "rtp_ıdle_frequency"
     */
    public function testPropertyRtpIdleFrequency()
    {
    }

    /**
     * Test attribute "handler_thread_pool_size"
     */
    public function testPropertyHandlerThreadPoolSize()
    {
    }
}
