<?php
/**
 * V2serversserverNamepublishersApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.14
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * V2serversserverNamepublishersApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class V2serversserverNamepublishersApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for deletePublisherConfig
     *
     * Deletes the specified Publisher configuration.
     *
     */
    public function testDeletePublisherConfig()
    {
    }

    /**
     * Test case for getPublisherConfig
     *
     * Retrieves the specified Publisher configuration.
     *
     */
    public function testGetPublisherConfig()
    {
    }

    /**
     * Test case for getPublishersConfig
     *
     * Retrieves the list of server Publishers.
     *
     */
    public function testGetPublishersConfig()
    {
    }

    /**
     * Test case for postPublisherConfig
     *
     * Adds the specified Publisher configuration.
     *
     */
    public function testPostPublisherConfig()
    {
    }

    /**
     * Test case for postPublishersConfig
     *
     * Adds a new Publisher to the list.
     *
     */
    public function testPostPublishersConfig()
    {
    }
}
