<?php
/**
 * V2serversApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.14
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * V2serversApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class V2serversApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getServerConfig
     *
     * Retrieves the Server configuration.
     *
     */
    public function testGetServerConfig()
    {
    }

    /**
     * Test case for getServerConfigAdv
     *
     * Retrieves the advanced Server configuration.
     *
     */
    public function testGetServerConfigAdv()
    {
    }

    /**
     * Test case for getServerLogFileConfig
     *
     * Retrieves the contents of a Server Log with the specified log name.
     *
     */
    public function testGetServerLogFileConfig()
    {
    }

    /**
     * Test case for getServerLogFileDownloadConfig
     *
     * Retrieves the Server Log file for the specified log name, zipped.
     *
     */
    public function testGetServerLogFileDownloadConfig()
    {
    }

    /**
     * Test case for getServerLogFilesConfig
     *
     * Retrieves the list of server log files.
     *
     */
    public function testGetServerLogFilesConfig()
    {
    }

    /**
     * Test case for getServerLogTypesConfig
     *
     * Retrieves the list of available server Log Types.
     *
     */
    public function testGetServerLogTypesConfig()
    {
    }

    /**
     * Test case for getServerLogsConfig
     *
     * Retrieves the contents of multiple Server Logs with the specified type in the log name.
     *
     */
    public function testGetServerLogsConfig()
    {
    }

    /**
     * Test case for getServersConfig
     *
     * Retrieves the list of Servers.
     *
     */
    public function testGetServersConfig()
    {
    }

    /**
     * Test case for getSourceDriverNamesList
     *
     * Get the list of source control drivers.
     *
     */
    public function testGetSourceDriverNamesList()
    {
    }

    /**
     * Test case for putServerAction
     *
     * Tells the Server to perform an action.
     *
     */
    public function testPutServerAction()
    {
    }

    /**
     * Test case for putServerConfig
     *
     * Updates the Server configuration.
     *
     */
    public function testPutServerConfig()
    {
    }

    /**
     * Test case for putServerConfigAdv
     *
     * Updates the advanced Server configuration.
     *
     */
    public function testPutServerConfigAdv()
    {
    }
}
